NAME = libft.a

LIB = ar rcs

RM = rm -f


CC = gcc


CFLAGS = -Wall -Werror -Wextra

INCLUDE = libft.h 

PRINTF = ft_printf_hex.c \
	ft_printf_pointer.c \
	ft_printf_put_nbr.c \
	ft_printf_str_char.c \
	ft_printf.c \
	ft_putnbr_unsinged.c \

GNL_SRC = get_next_line.c \

LIBFT_SRC = ft_isalpha.c \
	   ft_isdigit.c \
	   ft_isalnum.c \
	   ft_isascii.c \
	   ft_isprint.c \
	   ft_strlen.c \
	   ft_memset.c \
	   ft_bzero.c \
	   ft_memcpy.c \
	   ft_memmove.c \
	   ft_strlcpy.c \
	   ft_strlcat.c \
	   ft_strlen.c \
	   ft_toupper.c \
	   ft_tolower.c \
	   ft_strchr.c \
	   ft_strrchr.c \
	   ft_strncmp.c \
	   ft_memchr.c \
	   ft_memcmp.c \
	   ft_strnstr.c \
	   ft_atoi.c \
	   ft_calloc.c \
	   ft_strdup.c \
	   ft_substr.c \
	   ft_strjoin.c \
	   ft_strtrim.c \
	   ft_split.c \
	   ft_itoa.c \
	   ft_strmapi.c \
	   ft_striteri.c \
	   ft_putchar_fd.c \
	   ft_putstr_fd.c \
	   ft_putendl_fd.c \
	   ft_putnbr_fd.c \

BONUSSRC = ft_lstnew_bonus.c \
		   ft_lstadd_front_bonus.c \
		   ft_lstsize_bonus.c \
		   ft_lstlast_bonus.c \
		   ft_lstadd_back_bonus.c \
		   ft_lstdelone_bonus.c \
		   ft_lstclear_bonus.c \
		   ft_lstiter_bonus.c \
		   ft_lstmap_bonus.c \

PRINTF_SRC = $(addprefix ft_printf/, $(PRINTF))

SRC = $(LIBFT_SRC) $(PRINTF_SRC) $(GNL_SRC) $(BONUSSRC)

# BONUSOBJ = $(BONUSSRC:.c=.o)

OBJ = $(SRC:.c=.o)

all : $(NAME)
	@echo "done!!"

$(NAME): $(OBJ) $(INCLUDE)
	$(LIB) $(NAME) $(OBJ)

# .bonus: $(BONUSOBJ) $(INCLUDE)
# 	$(LIB) $(NAME) $(BONUSOBJ)
# 	@touch .bonus

# bonus: .bonus
# 	@echo "bonus done!!"

$.o : %.c
	$(CC) $(CCFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJ) $(BONUSOBJ)
	$(RM) .bonus

fclean: clean
	$(RM) $(NAME)

re: fclean all

rebonus: fclean bonus

.PHONY: all bonus clean fclean re
